### ISSUE TITLE
Concat -with option

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutate4l#10]
I've rewritten the concat to support a simple -with (since, in my mind this is concat and the original version is more like the unix cat command)  perhaps this will seem stupid when I understand more however 
= cc a1 -with b1
now results in a1+b1 in the new clip
if this is not ridiculous I could put together a pull. thanks.

**Comment by carrierdown** [comment]
Ah, thanks for the effort, but this is already supported. This isn't really documented well yet, so I can easily see why you decided to add this. However, concat already supports concatenating an arbitrary number of clips using the command =a1 a2 a3 aX concat. The reason why clips are specified first is because commands can be chained and thus it makes most sense to have them specified at the start of the "chain". This is mentioned briefly in the project readme, but it is not very clear at the moment, and concat is not documented at all yet, so...

**Comment by twobob** [comment]
makes sense. Appreciated. I'll tidy up my end
