### ISSUE TITLE
Enhancement: Invertable filters.

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutate4l#5]
Passing the arg -invert to a filter command would leave the result rather than deleting it.

Reasoning: Often less interesting passages contain longer note to accentuate cadence and the flourishes would be shorter.

I could look at this, if it is non trivial. Many thanks

**Comment by carrierdown** [comment]
That's a good idea. Feel free to submit a pull request for this. Adding options is very easy since reflection is used to autopopulate the options object passed into a command. You'll need to add a mapping from "-invert" to TokenType.Invert in the lexer, and add an Invert bool property on the options object in question.

**Comment by twobob** [comment]
Done.  I'll put together the pull
